### ISSUE TITLE
Unable to run project - The trust relationship between this workstation and the primary domain failed

### ISSUE THREAD

**Issue by janpluta** [episerver/alloy-mvc-template#22]
Hi,

This alloy hasnt been updated for the last 4 years and right now I am not even able to run it. I am getting this error

![image](https://user-images.githubusercontent.com/64965614/122552091-25726f00-d036-11eb-85f1-4fa355ffc911.png)

Can you fix it ? Because without this alloy its hard to test any new conception with Epi approach.

**Comment by barteksekula** [comment]
@janpluta IIS or IISExpress?

**Comment by janpluta** [comment]
IIS Express

**Comment by barteksekula** [comment]
Did you run visual studio as user with admin rights? Admin rights are needed to access localdb.
This repository works successfully in dozens of projects.
The stacktrace does not seem very related with episerver to be honest.

**Comment by janpluta** [comment]
Yes, I run it with admin rights. 
For me its not working and I switched to : https://marketplace.visualstudio.com/items?itemName=EPiServer.EpiserverCMSVisualStudioExtension
